[project]
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "ClaudeMetaResearch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.0.1,<26"
anthropic = ">=0.49.0,<0.50"
openai = ">=1.68.2,<2"
pyyaml = ">=6.0.2,<7"
networkx = ">=3.4.2,<4"
